apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "invincible-app.fullname" . }}-config
  labels:
    {{- include "invincible-app.labels" . | nindent 4 }}
    cloud: aws
data:
  DB_HOST: "{{ .Values.awsDbHost }}"
  DB_PORT: "{{ .Values.awsDbPort }}"
  DB_NAME: "{{ .Values.env.DB_NAME }}"
  DB_USER: "{{ .Values.env.DB_USER }}"
  ENVIRONMENT: "aws-production"
  CLOUD: "aws"
